# Generated by Django 5.1.2 on 2025-03-28 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_customuser_bank_customuser_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
